spring.application.name=spring-boot-rate-limit
resilience4j.ratelimiter.instances.apiRateLimit.limit-for-period=2
resilience4j.ratelimiter.instances.apiRateLimit.limit-refresh-period=60s
resilience4j.ratelimiter.instances.apiRateLimit.timeout-duration=0